# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82047eccf63faa52438e474b170037ec637d357a5c82e3abd745bda80dbd99f149e867cbf6f9dec9bbd2011218079cbd5f065ac360f09dda88ed28b6bfdf9ccb

test:
  secret_key_base: 5eabd3b8430f4a5fd7aaecf413d9c278dece3c189f4b218f36cef52759d28b76022ba82dd0112b547a8aa8c573bf77710388585d7215fde6590fad73f06a8b4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
